export const INCREMENT_HOURS = 'INCREMENT_HOURS';
export const DECREMENT_HOURS = 'DECREMENT_HOURS';

export const INCREMENT_MINUTES = 'INCREMENT_MINUTES';
export const DECREMENT_MINUTES = 'DECREMENT_MINUTES';
export const RESET_MINUTES = 'RESET_MINUTES';

export const INCREMENT_SECONDS = 'INCREMENT_SECONDS';
export const DECREMENT_SECONDS = 'DECREMENT_SECONDS';
export const RESET_SECONDS = 'RESET_SECONDS';

export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const RESET_TIMER = 'RESET_TIMER';