export const INCREMENT_HOURS = 'INCREMENT_HOURS';
export const INCREMENT_MINUTES = 'INCREMENT_MINUTES';
export const INCREMENT_SECONDS = 'INCREMENT_SECONDS';
export const DECREMENT_HOURS = 'DECREMENT_HOURS';
export const DECREMENT_MINUTES = 'DECREMENT_MINUTES';
export const DECREMENT_SECONDS = 'DECREMENT_SECONDS';